config/routes.rb
Development::Application.routes.draw do
  

  devise_for :users
  root "pins#index"
  get "about" => "pages#about" #create a comment about_path
  get "users/index" => "pages#users"
  get "users/show"
  resources :pins
  

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "2000x2000>", :thumb => "700x700>" }
	acts_as_likeable
	
	
	validates :locationBuilding, presence: true
	validates :clergyname, presence: true
	validates :concern, presence: true

	validates :locationBuilding, length: { minimum: 2 }
	validates :locationBuilding, length: { maximum: 255 }
	validates :clergyname, length: { minimum: 1 }
	validates :clergyname, length: { maximum: 255 }
	validates :concern, length: { minimum: 1 }
	validates :concern, length: { maximum: 255 }


	def self.search(search)
	 if search	
      	where('"locationBuilding" ILIKE ? OR concern ILIKE ? OR clergyname ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
	  else
	    scoped
	 end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  acts_as_liker

   validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def mypins
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    #@pins = Pin.where("name LIKE ?", "%#{params[:search]}%)
   
      @pins = Pin.all.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
 
  end

  

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Concern was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Concern was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this comment" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:locationBuilding, :concern, :image, :clergyname)
    end

    def sort_column
      params[:sort] || "concern" || "locationBuilding" || "clergyname"
    end
  
    def sort_direction
      params[:direction] || "asc"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	   
	   <%= link_to "THYWORSHIP", root_path, class: "navbar-brand" %>
	   <!--<h2><a class="navbar-brand" href="#">thyworship</a></h2>-->
	  </div>

	
	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav navbar-right">

	      
	      <li><%= link_to "HOME", root_path %></li>
	      <li><%= link_to "ABOUT/CONTACT", about_path %></li> 
	      <% if user_signed_in? %>
	      <li><%= link_to "SETTINGS", edit_user_registration_path %></li>
	      <li><%= link_to '+COMMENT', new_pin_path %></li>
          <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "SIGN IN", new_user_session_path %></li>
        <% end %>
	    </ul>

	  </div><!-- /.navbar-collapse -->
	 </nav>

app/views/layouts/about_html.erb
<h1>About us</h1>
<p>development page</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Development</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-success") %>
<% end %>
	<%= yield %>

</body>
</html>

app/views/pages/_home.html.erb
<!--<div class="jumbotron-">-->
	             
        <%= link_to "Log in", new_user_session_path, class: "btn btn-default" %>
      	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>

	
<!--</div>-->

app/views/pages/about.html.erb
<h1>About us</h1>
<h4>Speak up! Suggest a worship song. Thank your pastor or right a review on a church. <br/> 
<br/>
If you have a prayer request, feel free to post it up.  <br/>
<br/>
Vote for your pastor a person you think should receive some praise this week! Sned it in and after we tally<br/v>
<br/>
up the votes, we will see who wins the award! <br/>
<br/>
<br/>

Thanks everyone,
<br/>
<br/>
<h3><i>thyworship</i></h3><h4> staff </h4>
<br/>
<br/>


<address>
  <strong>Thyworship </strong><br>
  PO BOX 1882 <br>
  WOODINVILLE, WA 98072<br>
  
</address>

<address>
  <strong>Send Your Feedback and or Votes To: </strong><br>
  <a href="mailto:#">thyworshipmail@gmail.com</a>
</address>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          CHURCH OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
       
      <img src="http://i762.photobucket.com/albums/xx270/akimn89/bentleyblack_zps8cf18620.jpg" style="max-width:100%" alt="Milford Sound in New Zealand" />
        
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          PASTOR OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        Picture some good words, search keys, recent messages: titles.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          PASTOR'S SPOUSE OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse in">
      <div class="panel-body">
        Picture, what she/he does usually, how and why her/his congregation loves them.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          YOUTH PASTOR OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse in">
      <div class="panel-body">
        Years of service, congregation, what makes them different
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
          WORSHIP TEAM OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse in">
      <div class="panel-body">
        Church affiliation, members, how their different, concert schedule, style, testimony
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
          WORSHIP LEADER OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse in">
      <div class="panel-body">
        Name, church affiliated, style, picture
      </div>
    </div>
  </div>
   <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
          CHILDRENS MINISTRY OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse in">
      <div class="panel-body">
        pictures, church affiliation, staff that make it work, what are they doing differently
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseEight">
          ELDER OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse">
      <div class="panel-body">
        Church affiliated with, years of helping out the church, what they have done, picture
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseNine">
          PEOPLE'S CHOICE: MEMBER OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseNine" class="panel-collapse collapse in">
      <div class="panel-body">
        Church affiliated with, a few words to bless this person from our editor
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTen">
          MISSION FIELD MANAGER OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseTen" class="panel-collapse collapse in">
      <div class="panel-body">
        Where in the world, what they do, how long, what they are commited for, send us the money, we'll send it to them. For security purposes.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseEleven">
          BUSINESS OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseEleven" class="panel-collapse collapse in">
      <div class="panel-body">
        Business owner, what they serve, what church the owner is affiliated to, SPONSORED!
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwelve">
          RESTAURANT OF THE WEEK
        </a>
      </h4>
    </div>
    <div id="collapseTwelve" class="panel-collapse collapse in">
      <div class="panel-body">
        Business owner, what they serve, what church the owner is affiliated to, SPONSORED!
      </div>
    </div>
  </div>
</div>
  </div>


<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
	 <% if user_signed_in? %>
          # do something
     <% else %>
	<p>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>
  <% end %>      
</div>

app/views/pages/mypins.html.erb
<h1>my pins</h1>

<p>Need to figure this out</p>

app/views/pages/users.html.erb
<h1>my pins</h1>

<p>Need to figure this out</p>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



   <div class="form-group">
    <%= f.label "Church Name" %>
    <%= f.text_field :locationBuilding, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Clergy Name" %>
    <%= f.text_field :clergyname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Comment" %>
    <%= f.text_field :concern, as: :text, text_field_html: { rows: "3" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </br>
</br>
    <p>"Don't use the force, let it load." #fixthiscampus</p>
  </div>

<% end %>

app/views/pins/_pins.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <div class="actions center">
        <dl>
          <dt><h3><%= link_to pin.locationBuilding, pin_path(pin) %></h3></dt> <!--churchname-->
          <dt><%= pin.clergyname %></dt>
          <br>
          <dd><%= pin.concern %></dd><!--comment-->
          <br>
          <dd>by <%= pin.user.name if pin.user %></dd>
          <dt><h6><%= pin.created_at.strftime("%b %d, %Y") %></h6></dt></br>
          
          <% if pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-primary btn-xs"%>
          <%= link_to 'Delete', pin, class: "btn btn-primary btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>  </dt>
        <% end %>
        </div>
      	</dl>
    </div>
  <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
    <%= render 'pages/home' unless user_signed_in? %>
    <%= form_tag pins_path, :method => 'get' , :id => "pins_search" do %>
     
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil, class: "btn btn-default btn-xs"  %>
      </p>
      <!-- put sortable here-->

    <div id="pins">
        <%= render 'pins' %>
    </div>

    <div class="center">
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </div>

<% end %>

app/views/pins/new.html.erb
<h1>New Concern</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'BACK', pins_path %>
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<!--<%= image_tag @pin.image.url %>-->
				<!--<%= image_tag @pin.image.url(:medium) %>-->
				<p>
				  <!--<strong>Church Name:</strong><br>-->
				  <h2><%= @pin.locationBuilding %></h2>
				</p>

				<p>
				  <!--<strong>Pastor or Worship Leader Name:</strong><br>-->
				  <h4><%= @pin.clergyname %></h4>
				</p>

				<p>
				  <!--<strong>Comment:</strong>-->
				  <%= @pin.concern %>
				</p>

				<p><h5>
					by <%= @pin.user.name if @pin.user %></h5>
				</p>

				<p>
					<h6><%= @pin.created_at.strftime("%b %d, %Y") %></h6>
				</p>
			</br>

					<% if @pin.user == current_user %>	

					<%= link_to 'EDIT', edit_pin_path(@pin), class: "btn btn-primary btn-xs" %>
				
			</div>
				 
				<% end %>
				
			</div>
		</div>
	</div>
</div>

app/views/users/_index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/_show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>